# Generated by Django 5.1.6 on 2025-03-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data1', models.CharField(default='', max_length=50)),
                ('data2', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
