# Generated by Django 5.1.6 on 2025-03-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data1',
            new_name='Data1',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='data2',
            new_name='Data2',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='id',
            new_name='ID',
        ),
    ]
